Django/urls.py
import notifications.urls
from django.urls import path
from django.conf.urls import include
from app01 import views

app_name = "admin"
urlpatterns = [
    # 测试界面,可以绕过中间件（不用登陆）。仅作为测试功能用
    path('test/', views.test),

    # 登录界面
    path('login/', views.login),
    path('admin/login/', views.admin_login),
    path('logout/', views.logout, name='logout'),
    path('image/code/', views.verifycode),

    # 主界面（各类表格）
    # 用户表的相关url以及view
    path('user/list/', views.user_list),
    path('user/add/', views.user_add),
    path('user/<int:nid>/delete/', views.user_delete),
    path('user/<int:nid>/edit/', views.user_edit),

    # 宿舍表的相关url以及view
    path('dorm/add/', views.dorm_add),
    path('dorm/list/', views.dorm_list),
    path('dorm/find/lowE/', views.dorm_find_lowE),
    path('dorm/back/', views.dorm_back),
    path('dorm/<int:nid>/delete/', views.dorm_delete),
    path('dorm/<int:nid>/edit/', views.dorm_edit),

    # 管理人员的相关url以及views
    path('admin/list/', views.admin_list),

    # 留言板相关的url以及views
    path('article/list/', views.article_list),
    path('article/<int:nid>/detail/', views.article_detail),
    path('article/<int:nid>/delete/', views.article_delete),
    path('article/<int:nid>/edit/', views.article_edit),
    path('article/add/', views.article_add),

    # 评论模块相关的url以及views
    path('post/comment/<int:nid>', views.post_comment, name='comment'),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

app01/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
from mptt.models import MPTTModel, TreeForeignKey


# Create your models here.
class admin(models.Model):
    '''管理员表'''
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)


class DormInfo(models.Model):
    '''宿舍具体信息表'''
    dorm_id = models.SmallIntegerField(verbose_name="寝室号", unique=True, primary_key=True)
    accom_num = models.SmallIntegerField(verbose_name="应入住人数", default=0)
    on_canpus_num = models.SmallIntegerField(verbose_name="实际在校人数", default=0)
    administrator = models.CharField(verbose_name="寝室长", max_length=32)
    admin_mobile = models.CharField(verbose_name="寝室长电话号码", max_length=11)
    electric_charge = models.DecimalField(verbose_name="电费余额", max_digits=10, decimal_places=2, default=0)
    level_choices = (
        (1, "一星寝室"),
        (2, "二星寝室"),
        (3, "三星寝室"),
        (4, "优秀寝室"),
        (5, "最佳寝室")
    )
    level = models.SmallIntegerField(verbose_name="等级", choices=level_choices, default=1)


# 继承AbstractUser抽象类
class UserInfo(models.Model):
    '''人员表'''
    name = models.CharField(verbose_name='寝室人员姓名', max_length=16)
    password = models.CharField(verbose_name="  密码", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    account = models.DecimalField(verbose_name="账户余额", max_digits=10, decimal_places=2, default=0)
    create_time = models.DateField(verbose_name="入寝时间")  # 相比上一行，此行只有年月日，没有时分秒m

    # 部门id，有约束
    # to-表示与哪张表关联 tofield-表示与此表的哪一列关联
    # 使用foreignkey后，django会自动给字段名加一个_id
    # ondelete = models.CASCADE---级联删除
    # ondelete = models.SET_NULL---置空
    # depart = models.ForeignKey(to=Department, to_field="id", on_delete=models.CASCADE)
    gender_choices = (
        (1, "男"),
        (2, "女")
    )
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices)
    # 外键 链接的是宿舍表
    dorm = models.SmallIntegerField(verbose_name="寝室号", default=111)
    mobile = models.CharField(verbose_name="电话号码", max_length=11, default='00000000000')

    def __str__(self):
        return self.name


class ArticlePost(models.Model):
    '''留言信息表'''

    # 作者
    author = models.ForeignKey("UserInfo", on_delete=models.CASCADE, to_field='id')
    # 文章标题
    title = models.CharField(max_length=100)
    # 正文部分
    body = models.TextField()
    # 创建时间
    created = models.DateTimeField(default=timezone.now)
    # 更新时间
    updated = models.DateTimeField(auto_now=True)
    # 是否已经编辑过
    update_choices = (
        (1, "原始留言"),
        (2, "已编辑")
    )
    is_updated = models.SmallIntegerField(default=1, choices=update_choices)
    # 浏览量
    total_views = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title


class Comment(MPTTModel):
    '''评论表'''
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children'
    )
    reply_to = models.ForeignKey(
        UserInfo,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='replyers'
    )
    article = models.ForeignKey(
        ArticlePost,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name="评论的文章id"
    )
    user = models.ForeignKey(
        UserInfo,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name="评论的用户"
    )
    body = RichTextField(verbose_name="评论的文字")
    created = models.DateTimeField(auto_now_add=True, verbose_name="评论时间")

    class MPTTMeta:
        order_insertion_by = ['created']

    def __str__(self):
        return self.body[:20]

# 原评论留档
# class Comment(models.Model):
#     '''评论表'''
#
#     article = models.ForeignKey(
#         ArticlePost,
#         on_delete=models.CASCADE,
#         related_name='comments',
#         verbose_name="评论的文章id"
#     )
#     user = models.ForeignKey(
#         UserInfo,
#         on_delete=models.CASCADE,
#         related_name='comments',
#         verbose_name="评论的用户"
#     )
#     body = RichTextField(verbose_name="评论的文字")
#     created = models.DateTimeField(auto_now_add=True, verbose_name="评论时间")
#
#     class Meta:
#         ordering = ('created',)
#
#     def __str__(self):
#         return self.body[:20]

app01/views.py
import io
import random
from datetime import datetime

from PIL import Image, ImageDraw, ImageFont
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render, redirect, HttpResponse,get_object_or_404
from app01.utills.Pagination import Pagination
from app01.utills.form import *

from notifications.signals import notify

def admin_login(request):
    # 管理员登陆界面
    if request.method == "GET":
        form = AdminLoginForm()
        return render(request, 'admin_login.html', {'form': form})

    # 如果是post请求
    else:
        form = AdminLoginForm(data=request.POST)
        if form.is_valid():
            user_obj = models.admin.objects.filter(**form.cleaned_data).first()
            # 如果密码正确，并且是用户
            # 则需要写入到cookie和session中
            if models.admin.objects.filter(**form.cleaned_data).exists():
                # 如果验证码也输入正确，写入cookie和session
                if request.session["verifycode"] == request.POST.get("code"):
                    request.session["info"] = {'id': user_obj.id, "name": user_obj.username}
                    return redirect("/user/list")
                # 密码正确但是验证码错误
                else:
                    form.add_error("password", "验证码输入错误")
                    return render(request, 'admin_login.html', {'form': form})
            # 如果密码错误
            else:
                form.add_error("username", "用户名或密码错误")
                return render(request, 'admin_login.html', {'form': form})
        # 如果form中的元素不合规
        return render(request, 'admin_login.html', {'form': form})


def login(request):
    # 如果是get请求
    if request.method == "GET":
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    # 如果是post请求
    else:
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user_obj = models.UserInfo.objects.filter(**form.cleaned_data).first()
            # 如果密码正确，并且是用户
            # 则需要写入到cookie和session中
            if models.UserInfo.objects.filter(**form.cleaned_data).exists():
                # 如果验证码也输入正确，写入cookie和session
                if request.session["verifycode"] == request.POST.get("code"):
                    request.session["info"] = {'id': user_obj.id, "name": user_obj.name}
                    return redirect("/user/list")
                # 密码正确但是验证码错误
                else:
                    form.add_error("password", "验证码输入错误")
                    return render(request, 'login.html', {'form': form})
            # 如果密码错误
            else:
                form.add_error("name", "用户名或密码错误")
                return render(request, 'login.html', {'form': form})
        # 如果form中的元素不合规
        return render(request, 'login.html', {'form': form})


def logout(request):
    request.session.clear()
    return redirect("/login/")


def verifycode(request):
    bgcolor = (random.randrange(20, 100), random.randrange(20, 100), random.randrange(20, 100))
    width = 100
    height = 50
    # 创建画布
    im = Image.new('RGB', (width, height), bgcolor)
    # 创建画笔
    draw = ImageDraw.Draw(im)
    # 调用画笔的point()函数绘制噪点

    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fi = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fi)

    str = '1234567890QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm'
    rand_str = ''
    for i in range(0, 4):
        rand_str += str[random.randrange(0, len(str))]
    font = ImageFont.truetype("C:\Windows\Fonts\Gadugi.ttf", 40)
    fontcolor1 = (255, random.randrange(0, 255), random.randrange(0, 255))
    fontcolor2 = (255, random.randrange(0, 255), random.randrange(0, 255))
    fontcolor3 = (255, random.randrange(0, 255), random.randrange(0, 255))
    fontcolor4 = (255, random.randrange(0, 255), random.randrange(0, 255))

    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor1)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor2)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor3)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor4)
    del draw

    request.session['verifycode'] = rand_str

    buf = io.BytesIO()
    im.save(buf, 'png')
    return HttpResponse(buf.getvalue())


def test(request):
    return render(request, 'test.html')


def user_list(request):
    queryset = models.UserInfo.objects.all()
    page_obj = Pagination(request, queryset, page_size=10)
    page_queryset = page_obj.page_query
    page_str = page_obj.html()

    # 如果page有传递参数进来
    if request.GET.get('page'):
        # prev_url:处理的是分页系统中向前一页。
        # for_url处理的是分页系统中向后一页
        prev_url = '/user/list/?page={}'.format(int(request.GET.get('page')) - 1)
        for_url = '/user/list/?page={}'.format(int(request.GET.get('page')) + 1)
        return render(request, 'user_list.html',
                      {'queryset': page_queryset, 'page_str': page_str, 'prev_url': prev_url, 'for_url': for_url})
    # 没有page参数
    return render(request, 'user_list.html', {'queryset': page_queryset, 'page_str': page_str})


def user_add(request):
    if request.method == "GET":
        form = UserAddModelForm()
        return render(request, 'user_add.html', {"form": form})
    # 提交数据，需要校验
    else:
        form = UserAddModelForm(data=request.POST)
        if form.is_valid():
            # 如果数据合法，保存到数据库
            print(form.cleaned_data)
            # 自动保存，定义在哪个类就放在哪个类
            form.save()
            return redirect("/user/list/")
        else:
            # 校验失败
            print(form.errors)
            # 这里的form和初始的form不太相同，此处的form有data存在，若验证失败，还有错误信息
            return render(request, 'user_add.html', {"form": form})


def user_delete(request, nid):
    models.UserInfo.objects.filter(id=nid).delete()
    return redirect("/user/list/")


def user_edit(request, nid):
    if request.method == "GET":
        # 根据id去数据库获取要编辑的那行数据
        row_obj = models.UserInfo.objects.filter(id=nid).first()
        # 只需要将本行对象传入form，并且加一个instance=，那么form就会自动将所有信息填充在提交框中
        form = UserEditForm(instance=row_obj)
        return render(request, 'user_edit.html', {"form": form})
    else:
        # 在编辑中，需要告诉modelform到底是编辑哪一行数据，否则就会直接将数据添加在数据库中
        # 具体做法就是首先获取到数据后再将instance=row_obj装入
        row_object = models.UserInfo.objects.filter(id=nid).first()
        form = UserEditForm(data=request.POST, instance=row_object)  # 比添加多一个instance=rowobject
        if form.is_valid():
            form.save()
            return redirect("/user/list")
        else:
            return render(request, 'user_edit.html', {'form': form})


def dorm_list(request):
    queryset = models.DormInfo.objects.all()
    page_obj = Pagination(request, queryset, page_size=10)
    page_queryset = page_obj.page_query
    page_str = page_obj.html()

    # 如果page有传递参数进来
    if request.GET.get('page'):
        # prev_url:处理的是分页系统中向前一页。
        # for_url处理的是分页系统中向后一页
        prev_url = '/dorm/list/?page={}'.format(int(request.GET.get('page')) - 1)
        for_url = '/dorm/list/?page={}'.format(int(request.GET.get('page')) + 1)
        return render(request, 'dorm_list.html',
                      {'queryset': page_queryset, 'page_str': page_str, 'prev_url': prev_url, 'for_url': for_url})
    return render(request, 'dorm_list.html', {'queryset': page_queryset, 'page_str': page_str})


def dorm_find_lowE(request):
    # 快速找到电费低于100的视图函数
    conditions = {'electric_charge__lt': 100}
    queryset = models.DormInfo.objects.filter(**conditions).all()
    page_obj = Pagination(request, queryset, page_size=10)
    page_queryset = page_obj.page_query
    page_str = page_obj.html()
    return render(request, 'dorm_list.html', {'queryset': page_queryset, 'page_str': page_str})


def dorm_back(request):
    return redirect("/dorm/list/")


def dorm_delete(request, nid):
    models.DormInfo.objects.filter(id=nid).delete()
    return redirect("/dorm/list/")


def dorm_add(request):
    if request.method == "GET":
        form = DormForm()
        return render(request, 'dorm_add.html', {"form": form})
    # 提交数据，需要校验
    else:
        form = DormForm(data=request.POST)
        if form.is_valid():
            # 如果数据合法，保存到数据库
            print(form.cleaned_data)
            # 如果实际在校人数逻辑不符
            if form.cleaned_data['accom_num'] < form.cleaned_data['on_canpus_num']:
                form.add_error('on_canpus_num', "请注意实际在校人数是否正确")
                return render(request, 'dorm_add.html', {"form": form})
            # 自动保存，定义在哪个类就放在哪个类
            form.save()
            return redirect("/dorm/list/")
        else:
            # 校验失败
            print(form.errors)
            # 这里的form和初始的form不太相同，此处的form有data存在，若验证失败，还有错误信息
            return render(request, 'dorm_add.html', {"form": form})


def dorm_edit(request, nid):
    if request.method == "GET":
        # 根据id去数据库获取要编辑的那行数据
        row_obj = models.DormInfo.objects.filter(dorm_id=nid).first()
        # 只需要将本行对象传入form，并且加一个instance=，那么form就会自动将所有信息填充在提交框中
        form = DormForm(instance=row_obj)
        return render(request, 'user_edit.html', {"form": form})
    else:
        # 在编辑中，需要告诉modelform到底是编辑哪一行数据，否则就会直接将数据添加在数据库中
        # 具体做法就是首先获取到数据后再将instance=row_obj装入
        row_object = models.DormInfo.objects.filter(dorm_id=nid).first()
        form = DormForm(data=request.POST, instance=row_object)  # 比添加多一个instance=row_object
        if form.is_valid():
            form.save()
            return redirect("/dorm/list")
        else:
            return render(request, 'user_edit.html', {'form': form})


def admin_list(request):
    login_info = request.session['info']
    condition = {'username': login_info['name']}
    if models.admin.objects.filter(**condition).exists():

app01/templates/admin_list.html
{% extends 'layouts/basic_layout.html' %}

{% block title %} 管理员列表 {% endblock %}

{% block content %}

    <div>
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">管理员列表</h3>
            </div>
            <div class="panel-body">
                在这里可以增加，删除，修改，查询管理员的信息
            </div>
        </div>


        <div style="margin: 30px">
            <a class="btn btn-glow-dark btn-lg" href="/user/add/">新建管理员</a>
        </div>
    </div>
    <!-- Table -->
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>名称</th>
            <th>密码</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for obj in queryset %}
            <tr>
            <th>{{ obj.id }}</th>
            <td>{{ obj.username }}</td>
            <td>{{ obj.password }}</td>

            <td>
                <a style="margin-top: 2px" class="btn btn-primary btn-xs" href="/admin/{{ obj.id }}/edit/">编辑</a>
                <a style="margin-top: 2px" class="btn btn-danger btn-xs" href="/admin/{{ obj.id }}/delete/">删除</a>
            </td>
        {% endfor %}
    </table>

    {#images/user/avatar-1.jpg#}

    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li>
                <a href="{{ prev_url }}" aria-label="Previous">
                    <span aria-hidden="true">«</span>
                </a>
            </li>
            {{ page_str }}
            <li>
                <a href="{{ for_url }}" aria-label="Next">
                    <span aria-hidden="true">»</span>
                </a>
            </li>
        </ul>
        {#    /images/user/avatar-3#}
        <form method="get">
            <div class="col-lg-6" style="width: 200px;">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="输入页码" name="page">
                    <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">前往</button>
                    </span>
                </div><!-- /input-group -->
            </div>
        </form>
    </nav>

{% endblock %}

app01/templates/admin_login.html
{% extends "layouts/full_screen_lauout.html" %}

{% block title %} Login {% endblock %}

{% block content %}

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather icon-unlock auth-icon"></i>
                    </div>
                    <h3 class="mb-4">
                        管理员登录
                    </h3>

                    <span class="mb-0 text-muted">

                    </span>

                    <br/>
                    <br/>

                    <form role="form" method="post" novalidate>
                        {% csrf_token %}
                        <div class="input-group mb-3">
{#                            <input class="form-control" placeholder="请在此输入用户名">#}
                            {{ form.username }}
                            <span style="color: red">{{ form.name.errors.0 }}</span>
                        </div>

                        <div class="input-group mb-4">
                            {{ form.password }}
                            <span style="color: red">{{ form.password.errors.0 }}</span>
{#                            <input type="password" class="form-control" placeholder="请在此输入密码">#}
                        </div>

                        <div class="input-group mb-5">
                            <input type="text" class="form-control" placeholder="Verify(Case Sensitive)" name="code">
                            <img src="/image/code" id="image_code" style="width: 80px">
                        </div>

                        <div class="form-group text-left">
                            <div class="checkbox checkbox-fill d-inline">
                                <input type="checkbox" name="checkbox-fill-1" id="checkbox-fill-a1" checked="">
                                <label for="checkbox-fill-a1" class="cr">记住我</label>
                            </div>
                        </div>
                        <input type="submit" class="btn btn-primary shadow-2 mb-4"></input>

                    </form>
                    <br/>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

app01/templates/article_create.html
{% extends 'layouts/basic_layout.html' %}


{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

app01/templates/article_edit.html
{% extends 'layouts/basic_layout.html' %}

{% block title %}修改文章{% endblock %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

app01/templates/dorm_list.html
{% extends 'layouts/basic_layout.html' %}

{% block title %} 人员列表 {% endblock %}

{% block content %}
    {#    面板组#}
    <div>
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">宿舍详细信息列表</h3>
            </div>
            <div class="panel-body">
                在这里可以增加，删除，修改，查询宿舍的信息
            </div>
        </div>


        <div style="margin: 30px">
            <a class="btn btn-glow-dark btn-lg" href="/dorm/add/">新建宿舍</a>
            <a class="btn btn-glow-dark btn-lg" href="/dorm/find/lowE/">快捷查找低电费宿舍</a>
            <a class="btn btn-glow-dark btn-lg" href="/dorm/back/">返回宿舍列表</a>
        </div>


    </div>
    <!-- Table -->
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>应住</th>
            <th>实住</th>
            <th>寝室长</th>
            <th>寝室长电话</th>
            <th>电费</th>
            <th>宿舍星级</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for obj in queryset %}
            <tr>
            <th>{{ obj.dorm_id }}</th>
            <td>{{ obj.accom_num }}</td>
            <td>{{ obj.on_canpus_num }}</td>
            <td>{{ obj.administrator }}</td>
            <td>{{ obj.admin_mobile }}</td>
            <td>{{ obj.electric_charge }}</td>
            <td>{{ obj.get_level_display }}</td>

            <td>
                <a style="margin-top: 2px" class="btn btn-primary btn-xs" href="/dorm/{{ obj.dorm_id }}/edit/">编辑</a>
                <a style="margin-top: 2px" class="btn btn-danger btn-xs" href="/dorm/{{ obj.dorm_id }}/delete/">删除</a>
                <a style="margin-top: 2px" class="btn btn-attach btn-xs" href="/dorm/{{ obj.dorm_id }}/charge/">充电</a>
            </td>
        {% endfor %}
    </table>

    {#images/user/avatar-1.jpg#}

    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li>
                <a href="{{ prev_url }}" aria-label="Previous">
                    <span aria-hidden="true">«</span>
                </a>
            </li>
            {{ page_str }}
            <li>
                <a href="{{ for_url }}" aria-label="Next">
                    <span aria-hidden="true">»</span>
                </a>
            </li>
        </ul>


        {#快捷页码框#}
        <form method="get">
            <div class="col-lg-6" style="width: 200px;">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="输入页码" name="page">
                    <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">前往</button>
                    </span>
                </div><!-- /input-group -->
            </div>
        </form>
    </nav>

{% endblock %}

app01/templates/test.html
{% extends 'layouts/basic_layout.html' %}

{% block content %}


{% endblock %}

app01/templates/user_list.html
{% extends 'layouts/basic_layout.html' %}

{% block title %} 人员列表 {% endblock %}

{% block content %}
    {#处理弹窗信息#}
    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}

    <div>
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">住宿用户列表</h3>
            </div>
            <div class="panel-body">
                在这里可以增加，删除，修改，查询用户的信息
            </div>
        </div>


        <div style="margin: 30px">
            <a class="btn btn-glow-dark btn-lg" href="/user/add/">新建住宿用户</a>
        </div>
    </div>
    <!-- Table -->
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>名称</th>
            <th>年龄</th>
            <th>校园卡余额</th>
            <th>创建时间</th>
            <th>性别</th>
            <th>宿舍号</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for obj in queryset %}
            <tr>
            <th>{{ obj.id }}</th>
            <td>{{ obj.name }}</td>
            <td>{{ obj.age }}</td>
            <td>{{ obj.account }}</td>
            {#                            日期类模板语法的写法，区分python语法#}
            <td>{{ obj.create_time|date:"Y-m-d" }}</td>
            {#                            区分python元祖套元祖，注意没有括号#}
            <td>{{ obj.get_gender_display }}</td>
            <td>{{ obj.dorm }}</td>

            <td>
                <a style="margin-top: 2px" class="btn btn-primary btn-xs" href="/user/{{ obj.id }}/edit/">编辑</a>
                <a style="margin-top: 2px" class="btn btn-danger btn-xs" href="/user/{{ obj.id }}/delete/">删除</a>
                <a style="margin-top: 2px" class="btn btn-success btn-xs" href="/user/{{ obj.id }}/charge/">充值</a>
            </td>
        {% endfor %}
    </table>

    {#images/user/avatar-1.jpg#}

    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li>
                <a href="{{ prev_url }}" aria-label="Previous">
                    <span aria-hidden="true">«</span>
                </a>
            </li>
            {{ page_str }}
            <li>
                <a href="{{ for_url }}" aria-label="Next">
                    <span aria-hidden="true">»</span>
                </a>
            </li>
        </ul>
        {#    /images/user/avatar-3#}
        <form method="get">
            <div class="col-lg-6" style="width: 200px;">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="输入页码" name="page">
                    <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">前往</button>
                    </span>
                </div><!-- /input-group -->
            </div>
        </form>
    </nav>

{% endblock %}